name: ManasYemek
description: "App for yemekhane of Manas University"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  firebase_remote_config: ^6.1.2
  firebase_core: ^4.2.1
  permission_handler: ^11.3.1
  flutter_archive: ^6.0.4
  open_filex: ^4.7.0
  package_info_plus: ^9.0.0
  shimmer: ^3.0.0
  get_it: ^9.2.0
  intl: ^0.20.2
  dio: ^5.9.0
  provider: ^6.1.5+1
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  talker_dio_logger: ^5.1.5
  talker_flutter: ^5.1.5
  hive_ce_flutter: ^2.3.3

dev_dependencies:
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  hive_ce_generator: ^1.10.0
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  assets:
    - assets/fonts/

  fonts:
    - family: InstrumentSans
      fonts:
        - asset: assets/fonts/InstrumentSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/InstrumentSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/InstrumentSans-Bold.ttf
          weight: 700

  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#FFFFFF"       # фон splash screen
  image: "assets/splash_android12.png"  # изображение на splash
  android: true
  ios: true

  android_12:
    image: "assets/splash_android12.png"
    icon_background_color: "#FFFFFF"