name: ManasYemek
description: "App for yemekhane of Manas University"
publish_to: 'none'

version: 0.0.2+1

environment:
  sdk: ^3.8.1

dependencies:
  get_it: ^9.0.1
  intl: ^0.20.2
  dio: ^5.9.0
  provider: ^6.1.5+1
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  talker_dio_logger: ^5.0.2
  talker_flutter: ^5.0.2

dev_dependencies:
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  assets:
    - assets/fonts/

  fonts:
    - family: InstrumentSans
      fonts:
        - asset: assets/fonts/InstrumentSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/InstrumentSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/InstrumentSans-Bold.ttf
          weight: 700

  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#FFFFFF"       # фон splash screen
  image: "assets/splash_android12.png"  # изображение на splash
  android: true
  ios: true

  android_12:
    image: "assets/splash_android12.png"
    icon_background_color: "#FFFFFF"